# Generated by Django 5.2 on 2025-04-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(default='Anonymous', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
